export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const UPDATE_PURCHASABLE = 'UPDATE_PURCHASABLE';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';